### ISSUE TITLE
Override webflow

### ISSUE THREAD

**Issue by langedb** [Unicon/shib-mfa-duo-auth#8]
I tried putting a new duo-authn-webflow.xml into ${idp.home}/conf/authn/Duo, but it doesn't override the default distribution webflow config.  How can I make it do that?

**Comment by scalding** [comment]
Currently, this is not possible. See [https://github.com/Unicon/shib-mfa-duo-auth/blob/master/src/main/groovy/net/unicon/iam/shibboleth/idp/authn/duo/webflow/Config.groovy#L39-L40].

I see a couple options for this, though:
1. We could make those values properties that you could set in `duo.properties` or the like. This would likely be the easiest, but might require some configuration trickery.
2. We could work out what you're doing with the duo flow, and perhaps integrate it somehow, or at least provide a facility for it. This would likely require more work, but might provide for better future expansion.

**Comment by mapgrady** [comment]
JJ, if you are following the Shib Users list (which maybe you are), you'd see that David is changing this so that he can force a new password authentication in addition to a new Duo authn if an SP sends ForceAuthn. Right now, with Password only invoked as an Initial Authn, the Password does not get forced again when the SP sends ForceAuthn, only the Duo does. So, by suggestion of Scott Cantor, David is adding an additional invocation of the Password flow, as a subflow from the Duo flow, if ForceAuthn is set.

Seems like an option we want to provide "out of the box" in an easy way, so institutions can choose which interpretation they want to take on ForceAuthn -- re-force all the forms of authn that happened, including the 'initial one', or just those that happened after the initial one.

> On Aug 1, 2015, at 2:09 PM, Jj notifications@github.com wrote:
> 
> Currently, this is not possible. See [https://github.com/Unicon/shib-mfa-duo-auth/blob/master/src/main/groovy/net/unicon/iam/shibboleth/idp/authn/duo/webflow/Config.groovy#L39-L40 https://github.com/Unicon/shib-mfa-duo-auth/blob/master/src/main/groovy/net/unicon/iam/shibboleth/idp/authn/duo/webflow/Config.groovy#L39-L40].
> 
> I see a couple options for this, though:
> 
> We could make those values properties that you could set in duo.properties or the like. This would likely be the easiest, but might require some configuration trickery.
> We could work out what you're doing with the duo flow, and perhaps integrate it somehow, or at least provide a facility for it. This would likely require more work, but might provide for better future expansion.
> —
> Reply to this email directly or view it on GitHub https://github.com/Unicon/shib-mfa-duo-auth/issues/8#issuecomment-126946775.

## 

Michael A. Grady
IAM Architect, Unicon, Inc.

**Comment by langedb** [comment]
I believe what we are doing presently with the Duo flow is the correct behavior.  My issue is purely local in that I have to replicate current user experience.  I like the idea of the options in the duo.properties file, but that doesn't seem to mesh with how the rest of the IdP works in this respect.  What about modifying setup() in https://github.com/Unicon/shib-mfa-duo-auth/blob/master/src/main/groovy/net/unicon/iam/shibboleth/idp/authn/duo/webflow/Config.groovy to test and see if idp.home/conf/auth/Duo/ exists & if so, not loading ours?

**Comment by scalding** [comment]
Could you check what I have over in [https://github.com/Unicon/shib-mfa-duo-auth/tree/%238] to see if that's what you're looking for? To use a local file, you'd either create `${idp.home}/flows/authn/Duo/duo-authn-flow.xml` or `${idp.home}/flows/c14n/Duo/duo-c14n-flow.xml` (likely won't want to do the c14n).

**Comment by langedb** [comment]
Yes, that's doing what I needed. 

 Thanks

**Comment by scalding** [comment]
handled by [https://github.com/Unicon/shib-mfa-duo-auth/pull/10
